### ISSUE TITLE
Problem Input tags

### ISSUE THREAD

**Issue by ghost** [sonata-project/SonataNewsBundle#228]
The input tag is reduced, how to fix this?
![Image of Problem](http://image.noelshack.com/fichiers/2015/04/1421835429-logo.png
)

AppKernel
```
            new Knp\Bundle\MenuBundle\KnpMenuBundle(),
            new Sonata\CoreBundle\SonataCoreBundle(),
            new Sonata\BlockBundle\SonataBlockBundle(),

            // If you haven't already, add the storage bundle
            // This example uses SonataDoctrineORMAdmin but
            // it works the same with the alternatives
            new Sonata\DoctrineORMAdminBundle\SonataDoctrineORMAdminBundle(),

            // Then add SonataAdminBundle
            new Sonata\AdminBundle\SonataAdminBundle(),

            new OC\CoreBundle\OCCoreBundle(),

            new FOS\UserBundle\FOSUserBundle(),
            new Sonata\UserBundle\SonataUserBundle('FOSUserBundle'),
            new Application\Sonata\UserBundle\ApplicationSonataUserBundle(),

            new Sonata\EasyExtendsBundle\SonataEasyExtendsBundle(),

            new Sonata\MediaBundle\SonataMediaBundle(),
            new Application\Sonata\MediaBundle\ApplicationSonataMediaBundle(),

            new JMS\SerializerBundle\JMSSerializerBundle(),
            new Sonata\IntlBundle\SonataIntlBundle(),
            new FOS\RestBundle\FOSRestBundle(),

            new Sonata\ClassificationBundle\SonataClassificationBundle(),
            new Application\Sonata\ClassificationBundle\ApplicationSonataClassificationBundle(),

            new Ivory\CKEditorBundle\IvoryCKEditorBundle(),

            new Application\Sonata\NewsBundle\ApplicationSonataNewsBundle(),
            new Sonata\NewsBundle\SonataNewsBundle(),

            new Sonata\FormatterBundle\SonataFormatterBundle(),
            new Knp\Bundle\MarkdownBundle\KnpMarkdownBundle(),
```

Config.yml
```
sonata_news:
    title:        Sonata Project
    link:         http://sonata-project.org
    description:  Cool bundles on top of Symfony2
    salt:         'secureToken'
    permalink_generator: sonata.news.permalink.date # sonata.news.permalink.category

    comment:
        notification:
            emails:   [email@example.org, email2@example.org]
            from:     no-reply@sonata-project.org
            template: 'SonataNewsBundle:Mail:comment_notification.txt.twig'

sonata_formatter:
    formatters:
        markdown:
            service: sonata.formatter.text.markdown
            extensions:
                - sonata.formatter.twig.control_flow
                - sonata.formatter.twig.gist
                - sonata.media.formatter.twig

        text:
            service: sonata.formatter.text.text
            extensions:
                - sonata.formatter.twig.control_flow
                - sonata.formatter.twig.gist
                - sonata.media.formatter.twig

        rawhtml:
            service: sonata.formatter.text.raw
            extensions:
                - sonata.formatter.twig.control_flow
                - sonata.formatter.twig.gist
                - sonata.media.formatter.twig

        richhtml:
            service: sonata.formatter.text.raw
            extensions:
                - sonata.formatter.twig.control_flow
                - sonata.formatter.twig.gist
                - sonata.media.formatter.twig

ivory_ck_editor:
    configs:
        news:
            toolbar: [ [ "Source", "-", "Save" ], "/", [ "Anchor" ], "/", [ "Maximize" ] ]
            uiColor: "#000000"
            filebrowserUploadRoute: "my_route"
            extraPlugins: "wordcount"
```

composer.json
```
        "php": ">=5.3.3",
        "symfony/symfony": "2.3.*",
        "doctrine/orm": "~2.2,>=2.2.3",
        "doctrine/doctrine-bundle": "1.2.*",
        "twig/extensions": "1.0.*",
        "symfony/assetic-bundle": "2.3.*",
        "symfony/swiftmailer-bundle": "2.3.*",
        "symfony/monolog-bundle": "2.3.*",
        "sensio/distribution-bundle": "2.3.*",
        "sensio/framework-extra-bundle": "2.3.*",
        "sensio/generator-bundle": "2.3.*",
        "incenteev/composer-parameter-handler": "~2.0",

        "sonata-project/admin-bundle": "~2.3",
        "sonata-project/doctrine-orm-admin-bundle": "2.3.*@dev",
        "cocur/slugify": "dev-master",

        "coresphere/console-bundle": "dev-master",

        "friendsofsymfony/user-bundle": "~1.3",
        "sonata-project/easy-extends-bundle": "~2.1",
        "sonata-project/user-bundle": "2.3.x-dev",
        "sonata-project/datagrid-bundle": "~2.2@dev",
        "sonata-project/core-bundle": "2.2.*@dev",
        "sonata-project/media-bundle": "~2.2",
        "sonata-project/notification-bundle": "~2.2@dev",
        "sonata-project/intl-bundle": "2.2.*@dev",
        "sonata-project/classification-bundle": "2.2.*@dev",
        "sonata-project/news-bundle": "2.3.*@dev"
```
