### ISSUE TITLE
API Error: getPostsAction returns empty

### ISSUE THREAD

**Issue by delineas** [sonata-project/SonataNewsBundle#253]
Hi!

If we call this API request:
/api/news/posts.json

We get empty result

In function getPostsAction(ParamFetcherInterface $paramFetcher) if we change the return from
return $pager;
to
return $pager->getResults();

This change resolves the problem. But, Is it correct?

**Comment by core23** [comment]
Can you provide a PR, so we can have a look at your solution @delineas

**Comment by na-ji** [comment]
Same problem here... I think ideally the API should be returning not only the results, but also the current page, the number of results and the link to fetch the next and previous page.

**Comment by greg0ire** [comment]
This was introduced in ac7350a31f5d2a303958992af4fc3e2c90dd2a72 by @plouc , maybe he can explain how this is supposed to work… I guess there must be some kind of listener somewhere that produces a response from such a pager.

**Comment by na-ji** [comment]
There is maybe a listener for that, but the Pager is not serializable so only an empty object is returned in JSON.

**Comment by greg0ire** [comment]
I searched and searched and searched… from  news to core to datagrid back to news back to core back to datagrid again… and found [this](https://github.com/sonata-project/SonataDatagridBundle/blob/2.x/Resources/config/serializer/Pager.BasePager.xml). This is the thing that does not do its job. Can you have a look into that?

**Comment by greg0ire** [comment]
I think i should work by configuring jms serializer properly. Can you show us your configuration?

**Comment by na-ji** [comment]
I do not have any configuration for jms serializer (it is not needed for basic usage). What should I put un configuration ?

**Comment by greg0ire** [comment]
IMO you shouldn't have to do anything, the datagrid bundle should do it for you automatically.

But first let's try to make it work on your project : 

```yaml
jms_serializer:
    directories:
        sonata_datagrid:
            namespace_prefix: "Sonata\\DatagridBundle"
            path: "@SonataDatagridBundle/Resources/config/serializer"
```

**Comment by na-ji** [comment]
It is not working, even with this correct configuration and after enabling the bundle in the AppKernel
```yaml
jms_serializer:
    metadata:
        directories:
            sonata_datagrid:
                namespace_prefix: "Sonata\\DatagridBundle"
                path: "@SonataDatagridBundle/Resources/config/serializer"
```
