### ISSUE TITLE
Markdown won't parse media on production

### ISSUE THREAD

**Issue by roelveldhuizen** [sonata-project/SonataNewsBundle#73]
In production the markdown parser doesnot correctly parse the images. On production a `<% media 1, 'small'%>` tag is parsed to nothing. Just leaves the a blank space, so the literal tag is parsed but to nothing instead of an image. On dev it works correctly.

sonata_news.yml

```
sonata_news:
  title:        "Mon titre"
  link:         http://sonata-project.org
  description:  Cool bundles on top of Symfony2  
  salt:         'safdsadfsadfsadfsafd'

  comment:
    notification:
        emails:   [roelveldhuizen@harx.nl]
        from:     no-reply@harx.nl
        template: 'SonataNewsBundle:Mail:comment_notification.txt.twig'

doctrine:
  orm:
    entity_managers:
      default:
        #metadata_cache_driver: apc
        #query_cache_driver: apc
        #result_cache_driver: apc
        mappings:
          ApplicationSonataNewsBundle: ~
          SonataNewsBundle: ~

sonata_formatter:
    formatters:
        markdown:
            service: sonata.formatter.text.markdown
            extensions:
                - sonata.formatter.twig.control_flow
                - sonata.formatter.twig.gist
                - sonata.media.formatter.twig      

```

sonata_media.yml

```
sonata_media:
  db_driver: doctrine_orm
  default_context: default
  contexts:
    default: # the default context is mandatory
      providers:
        - sonata.media.provider.dailymotion
        - sonata.media.provider.youtube
        - sonata.media.provider.image
        - sonata.media.provider.file
        - sonata.media.provider.vimeo
      formats:
        small: { width: 715, quality: 95}
        big: { width: 1024 , quality: 95}
    category:      
      providers:
        - sonata.media.provider.image      
      formats:
          small: { width: 250 , quality: 95}
          big:   { width: 500 , quality: 90}
  cdn:
      server:
        path: /uploads/media # 
  filesystem:
      local:
        directory: %kernel.root_dir%/../web/uploads/media
        create: true

doctrine:
  orm:
    entity_managers:
      default:
        mappings:
          ApplicationSonataMediaBundle: ~
          SonataMediaBundle: ~
```

config_dev.yml

```

imports:
    - { resource: config.yml }

framework:
    router:   { resource: "%kernel.root_dir%/config/routing_dev.yml" }
    profiler: { only_exceptions: false }

web_profiler:
    toolbar: true
    intercept_redirects: false

monolog:
    handlers:
        main:
            type:  stream
            path:  %kernel.logs_dir%/%kernel.environment%.log
            level: debug
        firephp:
            type:  firephp
            level: info

assetic:
    use_controller: true
```

config_prod.yml

```

imports:
    - { resource: config.yml }

#doctrine:
#    orm:
#        metadata_cache_driver: apc
#        result_cache_driver: apc
#        query_cache_driver: apc

monolog:
    handlers:
        main:
            type:         fingers_crossed
            action_level: error
            handler:      nested
        nested:
            type:  stream
            path:  %kernel.logs_dir%/%kernel.environment%.log
            level: debug

```
